name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 0.4.0
repository: https://github.com/fluttercommunity/flutter_google_places
publish_to: none
environment:
  sdk: '>=2.23.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^2.0.0
  google_maps_webservice:
   git:
      url: https://github.com/zaman-pallob/google_maps_webservice.git
      ref: develop
  http: ^1.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
